name: tasks_todo_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.0
  table_calendar: ^3.0.9
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.2
  webview_flutter: ^4.4.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.2
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
