name: tasks_todo_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.3

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.0
  table_calendar: ^3.0.9
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.2
  webview_flutter: ^4.4.2
  intl: ^0.20.2
  flutter_native_splash: ^2.4.4
  google_fonts: ^6.2.1
  firebase_messaging: ^15.2.4
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.2
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  color: '#add8e6'
  image: 'assets/images/splash.png'
  color_dark: '#262626'
  image_dark: 'assets/images/splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#add8e6'
    image: 'assets/images/splash_android12.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/images/splash_android12.png'

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/images/
